---
AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Dynamo tables
Parameters:
  BucketName:
    Type: "String"
    Description: "Name of the Dynamo table"

Resources:
  CustomerDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "CustomerID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "CustomerID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  # Static S3 Web Hosting Bucket FrontEdn Deploy Assets
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: !Ref BucketName
    DeletionPolicy: Retain

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

Outputs:
  CustomerDynamoDBTableOutput:
    Description: "Customer DynamoDB Table"
    Value:
      !Ref CustomerDynamoDBTable
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CustomerDynamoDBTable"

  S3BucketName:
    Description: Name of S3 bucket to hold website content
    Value:
      !Ref S3Bucket
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3Bucket"

  S3BucketWebsiteUrl:
    Description: Returns the Amazon S3 website endpoint for the specificed bucket
    Value: !Join
      - ''
      - - 'http://'
        - !Ref S3Bucket
        - ".s3-website-"
        - !Ref AWS::Region
        - ".amazonaws.com"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3Bucket-WebsiteURL"
